-- huiwu.com — Supabase 建表
CREATE TABLE IF NOT EXISTS notes(id TEXT PRIMARY KEY,pos_x NUMERIC(5,2) NOT NULL DEFAULT 50.00,pos_y NUMERIC(5,2) NOT NULL DEFAULT 50.00,content TEXT DEFAULT '',rolled BOOLEAN NOT NULL DEFAULT false,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS settings(key_name TEXT PRIMARY KEY,value TEXT DEFAULT '');
ALTER TABLE notes ENABLE ROW LEVEL SECURITY;ALTER TABLE settings ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "allow_all_notes" ON notes;DROP POLICY IF EXISTS "allow_all_settings" ON settings;
CREATE POLICY "allow_all_notes" ON notes FOR ALL USING(true)WITH CHECK(true);
CREATE POLICY "allow_all_settings" ON settings FOR ALL USING(true)WITH CHECK(true);
INSERT INTO settings(key_name,value)VALUES('bg_image','')ON CONFLICT(key_name)DO NOTHING;
